### PR TITLE
App responsive container

### LINKED ISSUE #452: The application is taking up the entire screen width, no matter how large it is
**Describe the bug**
This issue is more like an improvement request than a bug.

Currently, the application is taking up the entire screen width, no matter how large it is. And this makes it to look very bad on very large screens. I work with a 34" screen, and herocast interface does not look it best on it. See below 👇

Screenshot 2024-08-07 at 15 35 37

I went further to simulate a much larger screen (9K) and this is how it looked
Screenshot 2024-08-07 at 15 37 15

**To Reproduce**
1. open [https://app.herocast.xyz/feeds](https://app.herocast.xyz/feeds) or run it locally and open it on large screen
2. You'll see that the application content is taking up the entire screen thereby making it look very bad 

**Expected behavior**
The Application should have a maximum width (depending on the screen size) that is center aligned. This will make the application look very good no matter the size of the screen it is being view on

It should look good on large screen like the site below 👇

Screenshot 2024-08-07 at 16 23 56

**Screenshots**
Included above

**Browser / OS / Deivce (help us fix this faster):**
Chrome and Arc on MacOS

**Additional context**
To fix this, we can use tailwind container with predefined max-width for different screen sizes to achieve this
Screenshot 2024-08-07 at 16 34 10

### PR DESCRIPTION
**Pull request by AjayiMike**
This PR addresses the issue of the uncontrolled width and layout of the application, which is perticularly noticeable on large screens

Preview of the fix: https://www.loom.com/share/e9ff06ee8c804ab38f314657957e8428?sid=2b81abc0-7da7-4ab1-b923-46ccae86de08

closes #452

### CODE REVIEW

**Comment by hellno** [comment]
thanks for the PR. the loom looks great 🙌🏼 

if you activate the formatting or linting for the project (I think it's four spaces), there will be a lot less changes and everything will be aligned with the rest of the project :)

**Comment by AjayiMike** [comment]
Okay, I will format the codebase and update the PR

**Comment by AjayiMike** [comment]
I just did. I'll open an issues to address the need to manually format the files and prevent future occurence.

**Comment by hellno** [comment]
looks great, thank you! 🙌🏼

**Pull request merged**
